#!/usr/bin/env python3
"""Render host worker definitions from the common semantic contract."""
from __future__ import annotations

import argparse
import importlib.util
import json
import re
import sys
import tomllib
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
CLASSIFIER_PATH = Path(__file__).resolve().parent / "delegation-classifier.py"


def _load_classifier() -> Any:
    specification = importlib.util.spec_from_file_location(
        "protocol_v2_classifier", CLASSIFIER_PATH
    )
    if not specification or not specification.loader:
        raise RuntimeError(f"cannot load classifier module: {CLASSIFIER_PATH}")
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


_CLASSIFIER = _load_classifier()
WORKER_TURN_LIMITS = _CLASSIFIER.WORKER_TURN_LIMITS
ROUTING_POLICY = _CLASSIFIER.ROUTING_POLICY
WORKER_PROFILES_PATH = REPO_ROOT / "agents" / "worker-profiles.json"
TOKEN = re.compile(r"{{([A-Z_]+)}}")


def paragraph_text(value: Any, name: str) -> str:
    if not isinstance(value, list) or not value or not all(isinstance(item, str) and item for item in value):
        raise ValueError(f"profile field {name!r} must be a non-empty string list")
    return "\n\n".join(value)


def render_body(template: str, host: dict[str, Any], output: dict[str, Any]) -> str:
    replacements = {
        "ESCALATION_CONTRACT": paragraph_text(
            host["escalation_contract"], "escalation_contract"
        ),
        "ROUTING_POLICY": ROUTING_POLICY,
        "RUNTIME_CONTRACT": runtime_contract(output),
        "LIFECYCLE_CONTRACT": paragraph_text(host["lifecycle_contract"], "lifecycle_contract"),
    }
    expected = set(TOKEN.findall(template))
    if expected != set(replacements):
        raise ValueError(f"template/profile token mismatch: expected={sorted(expected)} actual={sorted(replacements)}")
    body = TOKEN.sub(lambda match: replacements[match.group(1)], template).rstrip() + "\n"
    if TOKEN.search(body):
        raise ValueError("unresolved template token")
    return body


def profile_output(host: dict[str, Any], worker: dict[str, Any]) -> dict[str, Any]:
    output = host["output"]
    return {
        "format": output["format"],
        **worker,
    }


def worker_turn_limit(output: dict[str, Any]) -> int:
    tier = _CLASSIFIER.canonical_worker_name(output["name"])
    if tier is None or tier not in WORKER_TURN_LIMITS:
        raise ValueError(f"unknown worker profile: {output['name']!r}")
    limit = WORKER_TURN_LIMITS[tier]
    if type(limit) is not int or limit <= 0:
        raise ValueError(f"invalid worker turn limit: {limit!r}")
    return limit


def runtime_contract(output: dict[str, Any]) -> str:
    limit = worker_turn_limit(output)
    if output["format"] == "claude-markdown":
        return f"This profile's native agentic-turn limit is {limit} through maxTurns."
    if output["format"] == "pi-markdown":
        return (
            f"This profile has an advisory budget of {limit} agentic turns; Pi has "
            "no native per-worker turn-limit field. ADP separately enforces "
            f"{limit} tool-call attempts per identified worker lifetime through "
            "the Pi delegation enforcer extension, including attempts later "
            "denied. Tool calls are not agentic turns."
        )
    return (
        f"This profile has an advisory budget of {limit} agentic turns; Codex has "
        f"no native per-worker turn-limit field. ADP separately enforces {limit} "
        "PreToolUse tool-call attempts per identified worker lifetime, including "
        "resumes and attempts later denied. Tool calls are not agentic turns."
    )


def render_claude(body: str, description: str, output: dict[str, Any]) -> str:
    limit = worker_turn_limit(output)
    title = output["name"].replace("-", " ").title()
    return (
        "---\n"
        f"name: {output['name']}\n"
        f"description: {description}\n"
        f"model: {output['model']}\n"
        f"effort: {output['effort']}\n"
        f"maxTurns: {limit}\n"
        "---\n\n"
        "<!-- Generated by scripts/agents/render-bulk-workers.py; do not edit directly. -->\n\n"
        f"# {title}\n\n"
        + body
    )


def render_pi(body: str, description: str, output: dict[str, Any]) -> str:
    worker_turn_limit(output)
    title = output["name"].replace("-", " ").title()
    return (
        "---\n"
        f"name: {output['name']}\n"
        f"description: {description}\n"
        f"model: {output['model']}\n"
        "---\n\n"
        "<!-- Generated by scripts/agents/render-bulk-workers.py; do not edit directly. -->\n\n"
        f"# {title}\n\n"
        + body
    )


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_codex(body: str, description: str, output: dict[str, Any]) -> str:
    worker_turn_limit(output)
    if '"""' in body or "\\" in body:
        raise ValueError("Codex body contains a sequence unsafe for a TOML multiline basic string")
    rendered = (
        "# Generated by scripts/agents/render-bulk-workers.py; do not edit directly.\n"
        f"name = {toml_string(output['name'])}\n"
        f"description = {toml_string(description)}\n"
        f"model = {toml_string(output['model'])}\n"
        f"model_reasoning_effort = {toml_string(output['reasoning_effort'])}\n\n"
        "developer_instructions = \"\"\"\n"
        + body
        + "\"\"\"\n"
    )
    tomllib.loads(rendered)
    return rendered


def rendered_outputs() -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    source = json.loads(WORKER_PROFILES_PATH.read_text(encoding="utf-8"))
    if source.get("schema_version") != 2:
        raise ValueError(f"unsupported worker profile schema: {WORKER_PROFILES_PATH}")
    try:
        template_relative_path = Path(source["template"])
    except KeyError as exc:
        raise ValueError(f"missing worker template: {WORKER_PROFILES_PATH}") from exc
    if template_relative_path.is_absolute() or ".." in template_relative_path.parts:
        raise ValueError(f"template path must stay inside the repository: {template_relative_path}")
    template = (REPO_ROOT / template_relative_path).read_text(encoding="utf-8")
    for tier, tier_profile in source["tiers"].items():
        description = tier_profile["description"]
        for host_name, worker in tier_profile["profiles"].items():
            host = source["hosts"][host_name]
            output = profile_output(host, worker)
            body = render_body(template, host, output)
            if output["format"] == "claude-markdown":
                text = render_claude(body, description, output)
            elif output["format"] == "codex-toml":
                text = render_codex(body, description, output)
            elif output["format"] == "pi-markdown":
                text = render_pi(body, description, output)
            else:
                raise ValueError(f"unsupported output format: {output['format']}")
            relative_path = Path(output["path"])
            if relative_path.is_absolute() or ".." in relative_path.parts:
                raise ValueError(f"output path must stay inside the repository: {relative_path}")
            path = REPO_ROOT / relative_path
            if path in outputs:
                raise ValueError(f"duplicate output path: {path}")
            outputs[path] = text
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated workers are stale")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, expected in rendered_outputs().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
            print(path.relative_to(REPO_ROOT))
    if stale:
        for path in stale:
            print(f"stale generated worker: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        print("run scripts/agents/render-bulk-workers.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
