#!/usr/bin/env python3
"""Render host bulk-worker definitions from the common semantic contract."""
from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
TEMPLATE_PATH = REPO_ROOT / "agents" / "bulk-worker-common.md.tmpl"
PROFILES_PATH = REPO_ROOT / "agents" / "bulk-worker-profiles.json"
TOKEN = re.compile(r"{{([A-Z_]+)}}")


def paragraph_text(value: Any, name: str) -> str:
    if not isinstance(value, list) or not value or not all(isinstance(item, str) and item for item in value):
        raise ValueError(f"profile field {name!r} must be a non-empty string list")
    return "\n\n".join(value)


def render_body(template: str, profile: dict[str, Any]) -> str:
    replacements = {
        "HOST_NAME": profile["host_name"],
        "RUNTIME": profile["runtime"],
        "CONFIG_HOME": profile["config_home"],
        "PARENT_CHANNEL": profile["parent_channel"],
        "TASK_TRANSPORT_CONTRACT": paragraph_text(
            profile["task_transport_contract"], "task_transport_contract"
        ),
        "LAUNCH_CONTRACT": paragraph_text(profile["launch_contract"], "launch_contract"),
        "PERMISSION_CONTRACT": paragraph_text(profile["permission_contract"], "permission_contract"),
        "WAITING_CONTRACT": paragraph_text(profile["waiting_contract"], "waiting_contract"),
        "CONFLICT_CONTRACT": paragraph_text(profile["conflict_contract"], "conflict_contract"),
        "LIFECYCLE_CONTRACT": paragraph_text(profile["lifecycle_contract"], "lifecycle_contract"),
    }
    expected = set(TOKEN.findall(template))
    if expected != set(replacements):
        raise ValueError(f"template/profile token mismatch: expected={sorted(expected)} actual={sorted(replacements)}")
    body = TOKEN.sub(lambda match: replacements[match.group(1)], template).rstrip() + "\n"
    if TOKEN.search(body):
        raise ValueError("unresolved template token")
    return body


def render_claude(body: str, description: str, output: dict[str, Any]) -> str:
    return (
        "---\n"
        f"name: {output['name']}\n"
        f"description: {description}\n"
        f"model: {output['model']}\n"
        f"effort: {output['effort']}\n"
        f"maxTurns: {output['max_turns']}\n"
        "---\n\n"
        "<!-- Generated by scripts/agents/render-bulk-workers.py; do not edit directly. -->\n\n"
        "# Bulk Worker\n\n"
        + body
    )


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_codex(body: str, description: str, output: dict[str, Any]) -> str:
    if '"""' in body or "\\" in body:
        raise ValueError("Codex body contains a sequence unsafe for a TOML multiline basic string")
    rendered = (
        "# Generated by scripts/agents/render-bulk-workers.py; do not edit directly.\n"
        f"name = {toml_string(output['name'])}\n"
        f"description = {toml_string(description)}\n"
        f"model = {toml_string(output['model'])}\n"
        f"model_reasoning_effort = {toml_string(output['reasoning_effort'])}\n\n"
        "developer_instructions = \"\"\"\n"
        + body
        + "\"\"\"\n"
    )
    tomllib.loads(rendered)
    return rendered


def rendered_outputs() -> dict[Path, str]:
    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    source = json.loads(PROFILES_PATH.read_text(encoding="utf-8"))
    if source.get("schema_version") != 1:
        raise ValueError("unsupported bulk-worker profile schema")
    description = source["description"]
    outputs: dict[Path, str] = {}
    for profile in source["profiles"].values():
        output = profile["output"]
        body = render_body(template, profile)
        if output["format"] == "claude-markdown":
            text = render_claude(body, description, output)
        elif output["format"] == "codex-toml":
            text = render_codex(body, description, output)
        else:
            raise ValueError(f"unsupported output format: {output['format']}")
        relative_path = Path(output["path"])
        if relative_path.is_absolute() or ".." in relative_path.parts:
            raise ValueError(f"output path must stay inside the repository: {relative_path}")
        path = REPO_ROOT / relative_path
        if path in outputs:
            raise ValueError(f"duplicate output path: {path}")
        outputs[path] = text
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated workers are stale")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, expected in rendered_outputs().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
            print(path.relative_to(REPO_ROOT))
    if stale:
        for path in stale:
            print(f"stale generated worker: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        print("run scripts/agents/render-bulk-workers.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
